### ISSUE TITLE
请教关于redsocks2在NDK下编译的问题

### ISSUE THREAD

**Issue by edveen** [yanggis/proxy#1]
通过semigodking找到您，semigodking的redsock2提供的NDK编译wiki是您编写的，我按照教程一直编译通不过，主要是找不到您提到的文件，包括tsearch.c tdelete.c tdestroy.c tfind.c twalk.c和shadowsocks下面的openssl和libevent2，或者找到的也不对，始终编译通不过希望能提供一下编译所需文件，或者您直接新建一个可以编译通过的project，我来fork下。

**Comment by yanggis** [comment]
那个编译文件很久之前编译的，现在已经没有了， 不过我有编译好的二进制文件，发给你就不用编译了，在android系统上直接可以用。如果需要可以回复我。

**Comment by lmzmem** [comment]
太好了，终于等到您回复了，我其实也不需要编译，我就是要这个二进制文件，请发给我一份，如果您有conf文件也给我发一份吧谢谢，邮箱:lmzmem@163.com

**Comment by yanggis** [comment]
已经发你邮箱了。

**Comment by lmzmem** [comment]
收到了，非常感谢！我试过一下，确实可以跑起来，TCP协议没有问题，UDP协议不知道是什么情况还没通，UDP是否需要TPROXY配合

**Comment by yanggis** [comment]
UDP我不知道，我自己没用过UDP端口。

**Comment by lmzmem** [comment]
主要就是看中能透明代理UDP
