### ISSUE TITLE
不好意思，打扰了

### ISSUE THREAD

**Issue by wcmbeta** [yanggis/proxy#2]
没有找到你的联系方式，只好在这里留言，我有个repository误删了，然后owner变成了你（ 
  https://github.com/yanggis/fuckGFW    ）， 看看方便Transfer ownership 转回给我吗，非常感谢

**Comment by yanggis** [comment]
转给你的时候提示wcmbeta already has a repository in the yanggis/fuckGFW network

**Comment by wcmbeta** [comment]
我处理了，麻烦再试一下🙏

**Comment by wcmbeta** [comment]
OK了，非常感谢
